README.md
Would like a review to make sure my understanding of these fields is correct!
=> Clarification of a few fields on README

.gitignore, cloudflare-worker/.gitignore, cloudflare-worker/.vscode/extensions.json, cloudflare-worker/.vscode/settings.json, cloudflare-worker/README.md, cloudflare-worker/package.json, cloudflare-worker/src/handler.ts, cloudflare-worker/src/helpers/codecs.ts, cloudflare-worker/src/helpers/url.ts, cloudflare-worker/src/index.ts, cloudflare-worker/test/_setup.ts, cloudflare-worker/test/handler.ts, cloudflare-worker/test/tsconfig.json, cloudflare-worker/tsconfig.base.json, cloudflare-worker/tsconfig.json, cloudflare-worker/webpack.config.js, cloudflare-worker/yarn.lock
- separate test project
- `xo` for linting with some initial rules
- add vscode workspace settings and extension recommendations
=> clean up cloudflare worker lint and typescript config

cloudflare-worker/README.md
Add details for how cloudflare worker works into its README.
Closes #49
=> cloudflare workers readme update

src/public/index.html
Includes
* Show Default - graceful defaults
* Show Configured Single Column - fully customised config
* Show Configured Split Layout - customised config incl images
=> Improve demo page: bring back single/split

README.md
closes #99 
The tags are applying to certain props in a very specific ways. Do you think that it is clear with this addition to the doc?
=> feat: update readme with tags options

packages/donate-button-beta/src/components/widget/Frequency/index.tsx, packages/donate-button-beta/src/components/widget/NonprofitHeader/index.tsx, packages/donate-button-beta/src/components/widget/NonprofitInfo/index.tsx, packages/donate-button-beta/src/components/widget/index.tsx, packages/donate-button-beta/src/components/widget/theme/breakpoints.enum.ts, packages/donate-button-beta/src/components/widget/theme/colors.enum.ts, packages/donate-button-beta/src/index.tsx
closes #160 
This includes the changes from #163
=> feat: nonprofit info - layout desktop & mobile

packages/donate-button-beta/src/assets/chevron-down.svg, packages/donate-button-beta/src/components/widget/FormControl/index.tsx, packages/donate-button-beta/src/components/widget/Frequency/index.tsx, packages/donate-button-beta/src/components/widget/Input/index.tsx, packages/donate-button-beta/src/components/widget/Link/index.tsx, packages/donate-button-beta/src/components/widget/constants/supported-currencies.ts, packages/donate-button-beta/src/components/widget/index.tsx, packages/donate-button-beta/src/components/widget/theme/colors.enum.ts, packages/donate-button-beta/src/components/widget/types/currency.ts
=> feat::new-widget:donation input

packages/donate-button-beta/src/components/widget/FormControl/index.tsx, packages/donate-button-beta/src/components/widget/Frequency/index.tsx, packages/donate-button-beta/src/components/widget/SubmitButton/index.tsx, packages/donate-button-beta/src/components/widget/index.tsx, packages/donate-button-beta/src/components/widget/theme/colors.enum.ts, packages/donate-button-beta/src/components/widget/types/donation-frequency.ts
=> feat::new-widget:submit button

packages/donate-button-beta/src/assets/close.svg, packages/donate-button-beta/src/components/widget/Frequency/blocks/FrequencyPopoverContent/index.tsx, packages/donate-button-beta/src/components/widget/Frequency/index.tsx, packages/donate-button-beta/src/components/widget/Popover/index.tsx
=> feat::new-widget:frequency popover

packages/donate-button-beta/src/assets/chevron-down.svg, packages/donate-button-beta/src/assets/left-arrow.svg, packages/donate-button-beta/src/components/widget/CloseButton/index.tsx, packages/donate-button-beta/src/components/widget/CountryCard/index.tsx, packages/donate-button-beta/src/components/widget/CountrySelector/index.tsx, packages/donate-button-beta/src/components/widget/CountryTitle/index.tsx, packages/donate-button-beta/src/components/widget/CurrencySuggestion/index.tsx, packages/donate-button-beta/src/components/widget/Frequency/blocks/FrequencyPopoverContent/index.tsx, packages/donate-button-beta/src/components/widget/Frequency/index.tsx, packages/donate-button-beta/src/components/widget/Info/index.tsx, packages/donate-button-beta/src/components/widget/Input/index.tsx, packages/donate-button-beta/src/components/widget/Link/index.tsx, packages/donate-button-beta/src/components/widget/NonprofitHeader/index.tsx, packages/donate-button-beta/src/components/widget/NonprofitInfo/index.tsx, packages/donate-button-beta/src/components/widget/SectionContainer/index.tsx, packages/donate-button-beta/src/components/widget/SubmitButton/index.tsx, packages/donate-button-beta/src/components/widget/context/widget-context.ts, packages/donate-button-beta/src/components/widget/index.tsx, packages/donate-button-beta/src/components/widget/svg/ChevronDown/index.tsx, packages/donate-button-beta/src/components/widget/svg/Close/index.tsx, packages/donate-button-beta/src/components/widget/svg/LeftArrow/index.tsx, packages/donate-button-beta/src/components/widget/theme/borders.ts, packages/donate-button-beta/src/components/widget/theme/colors.ts, packages/donate-button-beta/src/components/widget/types/widget-config.ts, packages/donate-button-beta/src/helpers/options-types.ts, packages/donate-button-beta/src/public/index.html
- Limit the size of the widget
- Improve styles
- Default frequency configurable
- Initial message configurable
- Collapsable header on mobile screens
- Use primary color from config
=> feat::new-widget: style improvements & more configs

packages/donate-button-beta/src/components/widget/NonprofitHeader/index.tsx, packages/donate-button-beta/src/components/widget/NonprofitInfo/index.tsx, packages/donate-button-beta/src/components/widget/api/get-nonprofit-info.ts, packages/donate-button-beta/src/components/widget/index.tsx, packages/donate-button-beta/src/components/widget/types/nonprofit-info.ts, packages/donate-button-beta/src/components/widget/types/widget-config.ts, packages/donate-button-beta/src/public/index.html
Get `Logo` `Background image` and `name` from the API based on the provided slug
=> feat: get basic nonprofit info from the API

packages/donate-button-beta/src/components/widget/CountryCard/index.tsx, packages/donate-button-beta/src/components/widget/CountrySelector/index.tsx, packages/donate-button-beta/src/components/widget/CountryTitle/index.tsx, packages/donate-button-beta/src/components/widget/CurrencySuggestion/index.tsx, packages/donate-button-beta/src/components/widget/RedirectNotice/index.tsx, packages/donate-button-beta/src/components/widget/api/get-nonprofit-info.ts, packages/donate-button-beta/src/components/widget/context/widget-context.ts, packages/donate-button-beta/src/components/widget/index.tsx, packages/donate-button-beta/src/components/widget/types/donation-recipient.ts, packages/donate-button-beta/src/components/widget/types/nonprofit-info.ts, packages/donate-button-beta/src/components/widget/types/widget-config.ts, packages/donate-button-beta/src/helpers/construct-every-url.ts
Refactor the way that we use the countries to match with what we will receive from the Every's API
=> feat: refactor to use countries from every api

packages/donate-button-beta/src/components/widget/Frequency/index.tsx
=> fix: double border on frequency

packages/donate-button-beta/src/components/widget/Crypto/index.tsx, packages/donate-button-beta/src/components/widget/Frequency/blocks/FrequencyPopoverContent/index.tsx, packages/donate-button-beta/src/components/widget/Frequency/index.tsx, packages/donate-button-beta/src/components/widget/NonprofitInfo/index.tsx, packages/donate-button-beta/src/components/widget/index.tsx
=> feat: donate with crypto on the bottom right

packages/donate-button-beta/src/components/widget/CountryCard/index.tsx
=> feat: entire country clickable

packages/donate-button-beta/src/components/widget/CountrySelector/blocks/PaymentMethod/index.tsx
=> feat: no break line on payment methods

packages/donate-button-beta/src/components/widget/types/donation-frequency.ts, packages/donate-button-beta/src/helpers/markdown-to-html.ts, packages/donate-button-beta/src/public/index.html
closes #211 
closes #210 
closes #209
=> fix: onetime donation. chore: add demo text to faq & policies

packages/donate-button-beta/src/components/widget/NonprofitInfo/index.tsx, packages/donate-button-beta/src/components/widget/index.tsx
=> fix: improve layout. spacing to nonprofit text

packages/donate-button-beta/src/components/widget/CountryCard/index.tsx, packages/donate-button-beta/src/components/widget/CountrySelector/blocks/PaymentMethod/index.tsx, packages/donate-button-beta/src/components/widget/CountrySelector/index.tsx, packages/donate-button-beta/src/components/widget/CountryTitle/index.tsx, packages/donate-button-beta/src/components/widget/index.tsx
=> feat: improve country card & selector styles

packages/donate-button-beta/src/components/widget/CountrySelector/index.tsx, packages/donate-button-beta/src/components/widget/Input/index.tsx, packages/donate-button-beta/src/components/widget/index.tsx
=> feat: automatic change currency and country

packages/donate-button-beta/src/components/widget/Frequency/index.tsx
=> feat: change frequency selector styles:

packages/donate-button-beta/src/components/widget/CountryCard/index.tsx, packages/donate-button-beta/src/components/widget/NonprofitInfo/index.tsx, packages/donate-button-beta/src/components/widget/RedirectNotice/index.tsx, packages/donate-button-beta/src/components/widget/index.tsx, packages/donate-button-beta/src/public/index.html
=> feat: add button to open a widget for lilbubs. fix: style when description is short

packages/donate-button-v4/src/helpers/getCloudinaryUrl.ts
**Issues this will close**
- #322
=> Proper cloudinary flags

packages/donate-button-v4/src/components/widget/components/Checkbox/index.tsx, packages/donate-button-v4/src/components/widget/components/Checkbox/styles.ts, packages/donate-button-v4/src/components/widget/components/PaymentProcess/CryptoFlow/CryptoAmountInput.tsx, packages/donate-button-v4/src/components/widget/components/PaymentProcess/CryptoFlow/CryptoSelector.tsx, packages/donate-button-v4/src/components/widget/components/PaymentProcess/CryptoFlow/index.tsx, packages/donate-button-v4/src/components/widget/components/PaymentProcess/DafFlow/Views/DafAmountView.tsx, packages/donate-button-v4/src/components/widget/components/PaymentProcess/DefaultFlow/index.tsx, packages/donate-button-v4/src/components/widget/components/PaymentProcess/DonationAmount/index.tsx, packages/donate-button-v4/src/components/widget/components/PaymentProcess/DonationAmount/styles.ts, packages/donate-button-v4/src/components/widget/components/PaymentProcess/PrivateNote/index.tsx, packages/donate-button-v4/src/components/widget/components/PaymentProcess/StocksFlow/index.tsx, packages/donate-button-v4/src/components/widget/components/TextInput/TextArea.tsx, packages/donate-button-v4/src/components/widget/components/TextInput/TextInput.tsx, packages/donate-button-v4/src/components/widget/components/TextInput/index.tsx, packages/donate-button-v4/src/components/widget/components/TextInput/styles.ts, packages/donate-button-v4/src/components/widget/context/WidgetContext.tsx, packages/donate-button-v4/src/components/widget/hooks/useSubmitDonation.ts, packages/donate-button-v4/src/components/widget/icons/CheckMarkIcon.tsx, packages/donate-button-v4/src/helpers/constructDonateUrl.ts
**Screenshots or Screencaps**
|close|open|
|--|---|
|![0 0 0 0_8080_](https://user-images.githubusercontent.com/54896745/235444671-2790648c-dea4-42d6-aa50-b7e7fe8186b0.png)|![0 0 0 0_8080_ (1)](https://user-images.githubusercontent.com/54896745/235444674-f68a4426-3517-4679-92aa-9bb76a508580.png)|
=> Private note input

README.md
=> do not use self closing tag in readme

package.json, packages/donate-button-v4/src/components/widget/components/Checkbox/index.tsx, packages/donate-button-v4/src/helpers/parseDonateUrl.ts, packages/donate-button-v4/xo.config.js, yarn.lock
**Issues this will close**
- #359
=> Upgrade vercel builds to node 18

packages/donate-button-v4/src/components/widget/components/Faq/helpers.tsx, packages/donate-button-v4/src/components/widget/components/Faq/index.tsx, packages/donate-button-v4/src/components/widget/components/Footer/helpers.tsx, packages/donate-button-v4/src/components/widget/types/Nonprofit.ts
Add support for metadata.prefixWithThe #15701
=> Add support for metadata.prefixWithThe

packages/donate-button-v4/src/components/widget/components/NonprofitInfo/FundraiserCard.tsx, packages/donate-button-v4/src/components/widget/components/NonprofitInfo/NonprofitCard.tsx, packages/donate-button-v4/src/components/widget/components/NonprofitInfo/index.tsx, packages/donate-button-v4/src/components/widget/components/NonprofitInfo/styles.ts, packages/donate-button-v4/src/helpers/getCloudinaryUrl.ts, packages/donate-button-v4/src/public/index.html
**Brief description of changes**
Added Fundraiser Card
**Issues this will close**
- #377 
**Screenshots or Screencaps**
desktop:
mobile:
=> Fundraiser card

packages/donate-button-v4/src/components/widget/components/Faq/helpers.tsx, packages/donate-button-v4/src/components/widget/components/Faq/index.tsx, packages/donate-button-v4/src/components/widget/types/Nonprofit.ts
Updates donation FAQ wording depending on the nonprofits disbursement method.
=> Donation FAQ updates

README.md, packages/donate-button-v4/src/components/widget/components/PaymentProcess/DefaultFlow/index.tsx, packages/donate-button-v4/src/components/widget/components/PaymentProcess/DonationAmount/index.tsx, packages/donate-button-v4/src/components/widget/components/PaymentProcess/Frequency/index.tsx, packages/donate-button-v4/src/components/widget/components/PaymentProcess/PaymentMethodSelect/index.tsx, packages/donate-button-v4/src/components/widget/components/PaymentProcess/styles.ts, packages/donate-button-v4/src/components/widget/context/WidgetContext.tsx, packages/donate-button-v4/src/components/widget/types/WidgetConfig.ts, packages/donate-button-v4/src/helpers/optionsTypes.ts, packages/donate-button-v4/src/helpers/parseDonateUrl.ts, packages/donate-button-v4/src/public/index.html
**Brief description of changes**
Added fixed amount and frequency
**Screenshots or Screencaps**
|Fixed amount|Fixed frequency|Both fixed|
|---|---|---|
|![DevTools localhost](https://github.com/everydotorg/donate-button/assets/54896745/128205ff-97ae-4de5-ba1f-030a96bed767)|![DevTools localhost (1)](https://github.com/everydotorg/donate-button/assets/54896745/e8cf8270-2d89-4f98-b5bd-dd0b063e6006)|![DevTools localhost (2)](https://github.com/everydotorg/donate-button/assets/54896745/109f85cf-0f6d-43e5-b1f9-ea99504d5bd3)|
=> Fixed amount and frequency

packages/donate-button-v4/src/components/widget/components/PaymentProcess/CryptoFlow/index.tsx, packages/donate-button-v4/src/components/widget/components/PaymentProcess/DafFlow/Views/DafAmountView.tsx, packages/donate-button-v4/src/components/widget/components/PaymentProcess/DefaultFlow/index.tsx, packages/donate-button-v4/src/components/widget/components/PaymentProcess/DonationAmount/index.tsx, packages/donate-button-v4/src/components/widget/components/PaymentProcess/PublicTestimony/index.tsx, packages/donate-button-v4/src/components/widget/components/PaymentProcess/StocksFlow/index.tsx, packages/donate-button-v4/src/components/widget/context/WidgetContext.tsx, packages/donate-button-v4/src/components/widget/hooks/useSubmitDonation.ts, packages/donate-button-v4/src/helpers/constructDonateUrl.ts, packages/donate-button-v4/src/helpers/parseDonateUrl.ts
=> Add public testimony input

packages/donate-button-v4/src/components/widget/components/PaymentProcess/DonationAmount/index.tsx
|fixed amount and frequency|only fixed amount|
|---|---|
|![localhost_8080_ (3)](https://github.com/user-attachments/assets/1393f89b-4101-43f9-9c1b-3111aae738f0)|![localhost_8080_ (2)](https://github.com/user-attachments/assets/da07f074-7813-49ba-8082-18f182207448)|
=> FIX: amount text alignment

packages/donate-button-v4/src/components/widget/components/PaymentProcess/DonationAmount/index.tsx, packages/donate-button-v4/src/components/widget/components/PaymentProcess/StocksFlow/index.tsx, packages/donate-button-v4/src/components/widget/components/TextInput/TextInput.tsx, packages/donate-button-v4/src/components/widget/components/TextInput/styles.ts, packages/donate-button-v4/src/components/widget/hooks/useSubmitDonation.ts
=> Amount input error state

packages/donate-button-v4/src/components/widget/components/TextInput/styles.ts
=> Explicitly set the color for the text input

packages/donate-button-v4/src/components/widget/components/NonprofitInfo/styles.ts
Fix for - https://github.com/everydotorg/every.org/issues/17438
=> Fix - Bad logo for donate-button

packages/donate-button-v4/src/components/widget/components/PaymentProcess/DefaultFlow/index.tsx, packages/donate-button-v4/src/public/index.html
- Check fixedFrequency so that people can donate with Venmo
- Update example from /irc to /wphfund
=> Fix Venmo donations
